#!/bin/bash

echo "🚀 Railway Backend Deployment Script"
echo "===================================="
echo ""
echo "This script will guide you through deploying the backend to Railway."
echo ""
echo "Step 1: Open Railway Dashboard"
echo "Please go to: https://railway.app/dashboard"
echo ""
echo "Step 2: In your 'balanced-motivation' project, click 'New Service'"
echo "Choose 'Empty Service' and name it 'backend'"
echo ""
echo "Step 3: Once the service is created, run these commands:"
echo ""
echo "# Link to the backend service"
echo "railway link"
echo "# Select your project and the 'backend' service"
echo ""
echo "# Set environment variables"
echo "railway variables set DATABASE_URL=\"postgresql://postgres.igeuyfuxezvvenxjfnnn:Ai7v+%~%vDN.n"mD@aws-0-us-east-1.pooler.supabase.com:5432/postgres\""
echo "railway variables set META_APP_ID=\"1349075236218599\""
echo "railway variables set META_APP_SECRET=\"7c301f1ac1404565f26462e3c734194c\""
echo "railway variables set JWT_SECRET=\"ihtuAm6HBAOonQeYkO+FvjY8cxCABLSodMMUB8EqryI=\""
echo "railway variables set FRONTEND_URL=\"https://frontend-ten-eta-42.vercel.app\""
echo "railway variables set SUPABASE_URL=\"https://igeuyfuxezvvenxjfnnn.supabase.co\""
echo "railway variables set SUPABASE_ANON_KEY=\"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlnZXV5ZnV4ZXp2dmVueGpmbm5uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg0NjU1MjcsImV4cCI6MjA1NDA0MTUyN30.gVEXqUA5x_pLU0a2kKlTQFPsYsV8s0P8S2BzCRsZgw0\""
echo ""
echo "# Deploy the backend"
echo "railway up"
echo ""
echo "Step 4: Get your deployed URL"
echo "railway open"
echo ""
echo "Step 5: Update frontend with backend URL"
echo "cd ../frontend"
echo "npx vercel env add NEXT_PUBLIC_API_URL production"
echo "# Enter your Railway backend URL when prompted"
echo "npx vercel --prod"
echo ""
echo "That's it! Your backend should be deployed and connected to your frontend."